// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RsJkzEDqY1XXUzQKvXpSUIG9vL9Di00',
    appId: '1:644234667164:web:edf175baa8f9a3a20d3959',
    messagingSenderId: '644234667164',
    projectId: 'ummpark-9fdf4',
    authDomain: 'ummpark-9fdf4.firebaseapp.com',
    storageBucket: 'ummpark-9fdf4.firebasestorage.app',
    measurementId: 'G-JZMRDE0EPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAnTOQsoMdudVTUhp-tAgp0SuIAy-r7A',
    appId: '1:644234667164:android:16ae9838752cc3700d3959',
    messagingSenderId: '644234667164',
    projectId: 'ummpark-9fdf4',
    storageBucket: 'ummpark-9fdf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRpfVZxFp9UF1A63XMqqMxLMn2iUpQYM',
    appId: '1:644234667164:ios:9909f341942066e40d3959',
    messagingSenderId: '644234667164',
    projectId: 'ummpark-9fdf4',
    storageBucket: 'ummpark-9fdf4.firebasestorage.app',
    iosBundleId: 'com.example.ummparkir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRpfVZxFp9UF1A63XMqqMxLMn2iUpQYM',
    appId: '1:644234667164:ios:9909f341942066e40d3959',
    messagingSenderId: '644234667164',
    projectId: 'ummpark-9fdf4',
    storageBucket: 'ummpark-9fdf4.firebasestorage.app',
    iosBundleId: 'com.example.ummparkir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2RsJkzEDqY1XXUzQKvXpSUIG9vL9Di00',
    appId: '1:644234667164:web:b987a78429d18a9b0d3959',
    messagingSenderId: '644234667164',
    projectId: 'ummpark-9fdf4',
    authDomain: 'ummpark-9fdf4.firebaseapp.com',
    storageBucket: 'ummpark-9fdf4.firebasestorage.app',
    measurementId: 'G-XPKNYRS51V',
  );
}
